### ISSUE TITLE
How can I use phenomic in gitlab page?

### ISSUE THREAD

**Issue by the1900** [MoOx/phenomic#1012]
I could find *Automatically with Travis-CI*. but it looks like a little bit different with gitlab and travis.

**Comment by MoOx** [comment]
No idea. I tried recently but I failed :)

**Comment by the1900** [comment]
Sorry for my bad English, I think If these followed issues were handled then all clear. But I'm afraid to tell that I don't have any idea how to modify codes of phenomic.

1. we need the docker image which successfully runs `npm run build` with phenomic. The command makes artifacts in `dist` directory.

2. To do that *phenomic* should be installed without setting default theme containing produce *package.json*. it should be installed with written already `package.json` because of flavor such as custom css preprocessor, CNAME, additional npm library, etc. So install phenomic only with *well written package.json* makes possible to host on gitlab page I guess.

**Comment by MoOx** [comment]
phenomic only create a package.json when running setup command, which is only supposed to be run once, when you create the project.

**Comment by the1900** [comment]
Yeah, but what if I already have artifacts such as `AppContainer.js`, react components, sass  files, etc. and install phenomic on other machines with the artifacts then It would be overwritten when installing with default theme right?

**Comment by MoOx** [comment]
Are you trying to run the setup with already existing files? What's the goal of this?
If you have a custom base, you should probably not use setup command and just provide your own package.json default

**Comment by the1900** [comment]
Gitalb and github support pipeline which is CI like Travis so If I host the phenomic then the *yml file* will be like this. 

``` yml
image: **something contain NodeJs and NPM**
# If the container have phenomic then only run `npm run build`
# but if not install phenomic  via script below of pages section.

pages:
  script:
  - npm install phenomic #if phenomic isn't installed. It needs package.json 
  - npm run build
  artifacts:
    paths:
    - public
  only:
  - master #only master branch
```

Am I wrong? Now I'm confused.
