### ISSUE TITLE
Improve the way we consume collection(s) to avoid sending all metadata in all pages

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#713]
Related to trimming down the `window.collection`.  #712 

When you add in new custom meta (like in this blog post example) all those extra fields are also added to the `window.collection` data. This could potentially make it HUGE

Example:

`````` yaml

---
layout: Post
title: 'Defining Serverless and Why It Matters to Developers'
date: 2016-09-01
description: "You’ve probably heard the term _serverless._ But what does it actually mean? And more importantly, as a developer, why should you care?"
author:
  name: Serverless
  url: http://twitter.com/goServerless
  avatar: https://avatars3.githubusercontent.com/u/13742415?v=3&s=60
tags:
- serverless

---

```json
// printed in window.collection, notice the custom meta values
{
    "layout": "Post",
    "comments": true,
    "title": "Defining Serverless and Why It Matters to Developers",
    "date": "2016-09-01T00:00:00.000Z",
    "description": "You’ve probably heard the term _serverless._ But what does it actually mean? And more importantly, as a developer, why should you care?",
    "author": {
        "name": "Serverless",
        "url": "http://twitter.com/goServerless",
        "avatar": "https://avatars3.githubusercontent.com/u/13742415?v=3&s=60"
    },
    "tags": ["serverless"],
    "__filename": "blog/defining-serverless-and-why-it-matters-to-developers.md",
    "__url": "/blog/defining-serverless-and-why-it-matters-to-developers/",
    "__resourceUrl": "/blog/defining-serverless-and-why-it-matters-to-developers/index.html",
    "__dataUrl": "/blog/defining-serverless-and-why-it-matters-to-developers/index.html.bf1d5e0db467ef721b8508992749379b.json"
}
``````

All the data also exists in the `index.html.bf1d5e0db467ef721b8508992749379b.json` file. 

So the question is, **would it be possible/worth it** to remove the additional custom fields from outputting into `window.collection` and just have the .json files for the individual pages handle that additional data?
