### ISSUE TITLE
Deploy docs to surge.sh on each branch or at least master

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#755]
Since we've built docs on each commit, deploying docs to a live website is a right thing to do and it shouldn't make us to wait longer for build result. 

surge.sh is a good tools for doing this since all it takes to deploy a website is this 

```
surge dist
```

We can use a subdomain like: 

```
http://<branch>.build.phenomic.io
http://master.build.phenomic.io
http://docs-update.build.phenomic.io
```

I can handle this if you config DNS for phenomic.io correctly. See https://surge.sh/help/adding-a-custom-domain

**Comment by DavidWells** [comment]
Good idea.

We did this with travis:

```yml
sudo: false
language: node_js
node_js:
  - "4.4.1"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
deploy:
  - provider: script
    script: "scripts/deploy.sh"
    skip_cleanup: true
    on:
      branch: master
```

```bash
# deploy.sh
npm install surge
npm run build
surge --project ./dist --domain your-custom-surge-domain-here.surge.sh
```

Your surge credentials need to be setup in your CI system for this to work
